-- ---------------------------------------------------------------------------
-- Bootstrap the physiotherapy database on a LOCAL PostgreSQL server.
--
-- This is a TEMPLATE. `__APP_PASSWORD__` is a placeholder; it is never a real
-- credential, which is why this file is safe to commit.
--
-- To use it, generate a password and write a copy that is NOT tracked by git:
--
--   node -e "console.log(require('crypto').randomBytes(32).toString('hex'))" > .pgdump/app-role-password.txt
--   sed "s/__APP_PASSWORD__/$(cat .pgdump/app-role-password.txt)/g" \
--     scripts/bootstrap-local-db.sql > .pgdump/bootstrap-local-db.sql
--
-- Then run the copy as the "postgres" superuser. psql prompts for the
-- superuser password interactively, so it is never written to disk, never
-- passed on the command line, and never enters shell history:
--
--   psql -U postgres -h 127.0.0.1 -p 5432 -f .pgdump/bootstrap-local-db.sql
--
-- Idempotent: safe to run more than once.
-- ---------------------------------------------------------------------------

\set ON_ERROR_STOP on

-- 1. Application role -------------------------------------------------------
-- The application never connects as a superuser. It gets exactly one role,
-- owning exactly one database.
--
-- CREATEDB is granted because `prisma migrate dev` builds a temporary shadow
-- database to verify each new migration against. Without it, authoring the
-- next migration fails with a message that is hard to trace back to a
-- privilege problem.
DO $bootstrap$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'physio') THEN
    ALTER ROLE physio WITH LOGIN CREATEDB PASSWORD '__APP_PASSWORD__';
    RAISE NOTICE 'Role "physio" already existed - password and flags updated.';
  ELSE
    CREATE ROLE physio WITH LOGIN CREATEDB PASSWORD '__APP_PASSWORD__';
    RAISE NOTICE 'Role "physio" created.';
  END IF;
END
$bootstrap$;

-- 2. Database ---------------------------------------------------------------
-- CREATE DATABASE cannot run inside a transaction block, so the statement is
-- generated by a SELECT and executed by \gexec rather than wrapped in a DO
-- block. TEMPLATE template0 avoids inheriting anything from a customised
-- template1 on this machine.
SELECT 'CREATE DATABASE physio OWNER physio ENCODING ''UTF8'' TEMPLATE template0'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'physio')
\gexec

-- 3. Schema ownership -------------------------------------------------------
-- Since PostgreSQL 15 the public schema is no longer writable by PUBLIC.
-- Making the application role its owner is what allows Prisma to create
-- tables. Without this, `prisma migrate deploy` fails with "permission denied
-- for schema public".
\connect physio
ALTER SCHEMA public OWNER TO physio;
GRANT ALL ON SCHEMA public TO physio;

\echo ''
\echo 'Bootstrap complete. Role "physio" and database "physio" are ready.'
