import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { PaginationQueryDto } from '../../common/dto/pagination.dto';
import {
  IsIn,
  IsInt,
  IsOptional,
  IsString,
  Length,
  Max,
  MaxLength,
  Min,
} from 'class-validator';

/**
 * Caseload paging plus which side of the caseload to read.
 *
 * A dedicated DTO rather than a loose query parameter because the global
 * ValidationPipe runs with `forbidNonWhitelisted`, so anything not declared
 * here is rejected outright - which is exactly what caught `scope` being
 * passed without being described.
 */
export class CaseloadQueryDto extends PaginationQueryDto {
  @ApiPropertyOptional({
    enum: ['active', 'archived'],
    default: 'active',
    description:
      'archived lists discharged patients. That view carries no clinical ' +
      'detail - ending a link ends access to the record.',
  })
  @IsOptional()
  @IsIn(['active', 'archived'])
  scope?: 'active' | 'archived';
}

export class LinkPatientDto {
  @ApiProperty({
    example: 'K7M2QX9B',
    description: 'Single-use code generated by the patient.',
  })
  @IsString()
  @Length(6, 16)
  inviteCode!: string;
}

export class UpdateTherapistProfileDto {
  @ApiPropertyOptional({
    description: 'Self-declared. This system performs no licence verification.',
  })
  @IsOptional()
  @IsString()
  @MaxLength(64)
  licenseNumber?: string;

  @ApiPropertyOptional({ example: 'Musculoskeletal rehabilitation' })
  @IsOptional()
  @IsString()
  @MaxLength(120)
  specialization?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(1000)
  bio?: string;

  @ApiPropertyOptional({ minimum: 0, maximum: 70 })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(0)
  @Max(70)
  yearsExperience?: number;
}
